version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: housing_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-housing_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: housing_redis_cache
    ports:
      - "6379:6379"

  web:
    build: ./BE
    container_name: housing_django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./BE:/app
    ports:
      - "8000:8000"
    env_file:
      - ./BE/.env
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./BE
    container_name: housing_celery_worker
    command: celery -A housing_project worker --loglevel=info
    volumes:
      - ./BE:/app
    env_file:
      - ./BE/.env
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
