# Generated by Django 6.0.5 on 2026-05-21 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_favoriteproperty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.ManyToManyField(related_name='in_comparisons', to='properties.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='properties.property')),
            ],
            options={
                'indexes': [models.Index(fields=['landlord'], name='properties__landlor_704afe_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViewingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy'), ('COMPLETED', 'Đã hoàn thành')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_appointments', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_appointments', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='properties.property')),
            ],
            options={
                'ordering': ['-appointment_date'],
                'indexes': [models.Index(fields=['guest', 'status'], name='properties__guest_i_ee1ece_idx'), models.Index(fields=['landlord', 'status'], name='properties__landlor_10a567_idx'), models.Index(fields=['appointment_date'], name='properties__appoint_d50a8e_idx')],
            },
        ),
    ]
