# Generated by Django 6.0.5 on 2026-05-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created",
            new_name="created_at",
        ),
    ]
