# Generated by Django 6.0.5 on 2026-05-15 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slot_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_booked", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Time Slot",
                "db_table": "time_slots",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient", "Bệnh nhân"),
                            ("doctor", "Bác sĩ"),
                            ("admin", "Quản trị viên"),
                        ],
                        default="patient",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="CREATE / UPDATE / DELETE / LOGIN …",
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=60)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "diff",
                    models.JSONField(
                        default=dict, help_text="Trước và sau khi thay đổi"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="clinics/"),
                ),
            ],
            options={
                "verbose_name": "Clinic",
                "db_table": "clinics",
                "indexes": [
                    models.Index(fields=["name"], name="clinics_name_040576_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("general", "Đa khoa"),
                            ("cardiology", "Tim mạch"),
                            ("dermatology", "Da liễu"),
                            ("pediatrics", "Nhi khoa"),
                            ("neurology", "Thần kinh"),
                            ("orthopedics", "Cơ xương khớp"),
                            ("ent", "Tai mũi họng"),
                            ("ophthalmology", "Mắt"),
                            ("psychiatry", "Tâm thần"),
                            ("other", "Khác"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                ("bio", models.TextField(blank=True)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "is_accepting_new",
                    models.BooleanField(
                        default=True, help_text="Có nhận bệnh nhân mới không"
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="app.clinic",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "db_table": "doctors",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xác nhận"),
                            ("confirmed", "Đã xác nhận"),
                            ("cancelled", "Đã huỷ"),
                            ("completed", "Đã khám xong"),
                            ("no_show", "Vắng mặt"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True, help_text="Triệu chứng bệnh nhân mô tả"
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Ghi chú thêm")),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="app.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "db_table": "appointments",
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "generic_name",
                    models.CharField(
                        blank=True, help_text="Tên hoạt chất", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("antibiotic", "Kháng sinh"),
                            ("analgesic", "Giảm đau"),
                            ("antiviral", "Kháng virus"),
                            ("antifungal", "Kháng nấm"),
                            ("vitamin", "Vitamin"),
                            ("supplement", "Thực phẩm bổ sung"),
                            ("cardiovascular", "Tim mạch"),
                            ("other", "Khác"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="viên",
                        help_text="Đơn vị: viên, ml, gói …",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("side_effects", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Drug",
                "db_table": "drugs",
                "indexes": [
                    models.Index(fields=["name"], name="drugs_name_775e1b_idx"),
                    models.Index(
                        fields=["category", "is_active"],
                        name="drugs_categor_d813be_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diagnosis", models.TextField(help_text="Chẩn đoán")),
                (
                    "treatment_plan",
                    models.TextField(blank=True, help_text="Phác đồ điều trị"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Ghi chú thêm của bác sĩ"),
                ),
                (
                    "follow_up_date",
                    models.DateField(blank=True, help_text="Ngày tái khám", null=True),
                ),
                (
                    "attachments",
                    models.JSONField(
                        default=list, help_text="Danh sách URL file đính kèm"
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to="app.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "db_table": "medical_records",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")],
                        max_length=2,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A Pos"),
                            ("A-", "A Neg"),
                            ("B+", "B Pos"),
                            ("B-", "B Neg"),
                            ("AB+", "Ab Pos"),
                            ("AB-", "Ab Neg"),
                            ("O+", "O Pos"),
                            ("O-", "O Neg"),
                        ],
                        max_length=3,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("insurance_number", models.CharField(blank=True, max_length=50)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("allergies", models.TextField(blank=True, help_text="Dị ứng đã biết")),
                (
                    "chronic_diseases",
                    models.TextField(blank=True, help_text="Bệnh mãn tính"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "db_table": "patients",
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="app.patient",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("transfer", "Chuyển khoản"),
                            ("momo", "MoMo"),
                            ("vnpay", "VNPay"),
                            ("insurance", "Bảo hiểm y tế"),
                        ],
                        default="cash",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ thanh toán"),
                            ("paid", "Đã thanh toán"),
                            ("refunded", "Đã hoàn tiền"),
                            ("failed", "Thất bại"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Mã giao dịch từ cổng thanh toán",
                        max_length=100,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="app.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Hướng dẫn chung của đơn thuốc"
                    ),
                ),
                (
                    "is_dispensed",
                    models.BooleanField(default=False, help_text="Đã phát thuốc chưa"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="app.doctor",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="app.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "db_table": "prescriptions",
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="Liều dùng mỗi lần, vd: 500mg", max_length=50
                    ),
                ),
                ("quantity", models.PositiveIntegerField(help_text="Số lượng")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("1x/ngày", "1 lần/ngày"),
                            ("2x/ngày", "2 lần/ngày"),
                            ("3x/ngày", "3 lần/ngày"),
                            ("4x/ngày", "4 lần/ngày"),
                            ("khi cần", "Khi cần"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(
                        default=7, help_text="Số ngày dùng"
                    ),
                ),
                (
                    "special_note",
                    models.CharField(
                        blank=True, help_text="Lưu ý riêng", max_length=200
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescription_items",
                        to="app.drug",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Item",
                "db_table": "prescription_items",
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment",
                to="app.timeslot",
            ),
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Thứ 2"),
                            (1, "Thứ 3"),
                            (2, "Thứ 4"),
                            (3, "Thứ 5"),
                            (4, "Thứ 6"),
                            (5, "Thứ 7"),
                            (6, "Chủ nhật"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "slot_duration_min",
                    models.PositiveSmallIntegerField(
                        default=30, help_text="Thời gian mỗi slot (phút)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to="app.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Schedule",
                "db_table": "work_schedules",
            },
        ),
        migrations.AddField(
            model_name="timeslot",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_slots",
                to="app.workschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "is_active"], name="users_email_a7cfd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name", "object_id"], name="audit_logs_model_n_656046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "created_at"], name="audit_logs_user_id_fbfd51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["specialty"], name="doctors_special_fd5ec6_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["clinic", "is_accepting_new"], name="doctors_clinic__b5fe02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "paid_at"], name="payments_status_ed0c90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["record", "issued_at"], name="prescriptio_record__69342c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_6fe260_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "status"], name="appointment_doctor__45f502_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["booked_at"], name="appointment_booked__3ca604_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workschedule",
            index=models.Index(
                fields=["doctor", "weekday", "is_active"],
                name="work_schedu_doctor__831e29_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workschedule",
            unique_together={("doctor", "weekday", "start_time")},
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["slot_date", "is_booked"], name="time_slots_slot_da_f3b068_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["schedule", "slot_date"], name="time_slots_schedul_c00a07_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("schedule", "slot_date", "start_time")},
        ),
    ]
