# Generated by Django 6.0.5 on 2026-05-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="category",
            field=models.CharField(
                choices=[
                    ("antibiotic", "Kháng sinh"),
                    ("analgesic", "Giảm đau"),
                    ("antiviral", "Kháng virus"),
                    ("antifungal", "Kháng nấm"),
                    ("vitamin", "Vitamin"),
                    ("supplement", "Thực phẩm bổ sung"),
                    ("cardiovascular", "Tim mạch"),
                    ("other", "Khác"),
                ],
                default="other",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="unit",
            field=models.CharField(
                default="viên", help_text="Đơn vị: viên, ml, gói …", max_length=200
            ),
        ),
    ]
