# Generated by Django 6.0.5 on 2026-05-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_company_interns_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='interns',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
