name: Run Tests

on:
  push:
    branches:
      - nguyen_day11

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run test
        run: |
          python -m unittest ngay11.bai14